// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGFcfrSPjEyRqYG55_rvW_ZqJJxVDLaM',
    appId: '1:835613554586:web:601ea70c4fcef716a0ec23',
    messagingSenderId: '835613554586',
    projectId: 'mytown-tallapoosa',
    authDomain: 'mytown-tallapoosa.firebaseapp.com',
    storageBucket: 'mytown-tallapoosa.firebasestorage.app',
    measurementId: 'G-EQP4ZTSDN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfH1WpiKFhzmD82ZbF7wXyAU7kvtoTDiM',
    appId: '1:835613554586:android:089e49db1e99e73ba0ec23',
    messagingSenderId: '835613554586',
    projectId: 'mytown-tallapoosa',
    storageBucket: 'mytown-tallapoosa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpy5AjccRL2n5G93QDXwxDfaffQ3PPT0',
    appId: '1:835613554586:ios:326a4b2f1b032f09a0ec23',
    messagingSenderId: '835613554586',
    projectId: 'mytown-tallapoosa',
    storageBucket: 'mytown-tallapoosa.firebasestorage.app',
    androidClientId: '835613554586-ebrta1ntvlskgqicpg8vgpcctnk03fbt.apps.googleusercontent.com',
    iosClientId: '835613554586-947er3t3mupcvpqtmd99v93soo3121nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytownAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpy5AjccRL2n5G93QDXwxDfaffQ3PPT0',
    appId: '1:835613554586:ios:326a4b2f1b032f09a0ec23',
    messagingSenderId: '835613554586',
    projectId: 'mytown-tallapoosa',
    storageBucket: 'mytown-tallapoosa.firebasestorage.app',
    androidClientId: '835613554586-ebrta1ntvlskgqicpg8vgpcctnk03fbt.apps.googleusercontent.com',
    iosClientId: '835613554586-947er3t3mupcvpqtmd99v93soo3121nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytownAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeGFcfrSPjEyRqYG55_rvW_ZqJJxVDLaM',
    appId: '1:835613554586:web:78f9dc29a5e683c3a0ec23',
    messagingSenderId: '835613554586',
    projectId: 'mytown-tallapoosa',
    authDomain: 'mytown-tallapoosa.firebaseapp.com',
    storageBucket: 'mytown-tallapoosa.firebasestorage.app',
    measurementId: 'G-0B5ECWQMFE',
  );
}
